spring.application.name=expensetracker
spring.datasource.url=jdbc:mysql://localhost:3306/expense_tracker?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=p8!Gv3#rQw9zK2@t
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080